import { colors } from "./colors";
import { MD3LightTheme, configureFonts } from "react-native-paper";

const fontConfig = {

  default: {
    fontFamily: "Nunito_400Regular",
  },

  labelSmall: {
    fontFamily: "Nunito_700Bold",
  },
  labelMedium: {
    fontFamily: "Nunito_700Bold",
  },
  labelLarge: {
    fontFamily: "Nunito_700Bold",
  },

  bodySmall: {
    fontFamily: "Nunito_400Regular",
  },
  bodyMedium: {
    fontFamily: "Nunito_400Regular",
  },
  bodyLarge: {
    fontFamily: "Nunito_400Regular",
  },

  titleSmall: {
    fontFamily: "Nunito_600SemiBold",
  },
  titleMedium: {
    fontFamily: "Nunito_600SemiBold",
  },
  titleLarge: {
    fontFamily: "Nunito_600SemiBold",
  },
};

export const light = {
  ...MD3LightTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.dark,
    onPrimary: colors.light,
    primaryContainer: colors.dark,
    onPrimaryContainer: colors.light,

    primary1: colors.dark9,
    primary2: colors.dark8,
    primary3: colors.dark7,
    primary4: colors.dark4,
    primary5: colors.dark5,
    primary6: colors.dark6,
    primary7: colors.dark7,
    primary8: colors.dark8,
    primary9: colors.dark9,
    primary10: colors.dark10,
    primary11: colors.dark11,
    primary12: colors.dark12,

    suface: colors.light2,

    secondary: colors.dark6,
    onSecondary: colors.light,
    secondaryContainer: colors.dark6,
    onSecondaryContainer: colors.light,

    error: colors.red,
    onError: colors.light,
    errorContainer: colors.red1,
    onErrorContainer: colors.red,

    background: colors.light,
    onBackground: colors.dark,
    surface: colors.light5,
    onSurface: colors.dark,

    background1: colors.light1,
    background2: colors.light2,
    background3: colors.light3,
    background4: colors.light4,
    background5: colors.light5,
    background6: colors.light6,
    background7: colors.light7,
    background8: colors.light8,
    background9: colors.light9,
    background10: colors.light10,
    background11: colors.light11,
    background12: colors.light12,

    color: colors.dark,
    color1: colors.dark9,
    color2: colors.dark8,
    color3: colors.dark7,
    color4: colors.dark6,
    color5: colors.dark5,
    color6: colors.dark4,
    color7: colors.dark3,
    color8: colors.dark2,
    color9: colors.dark1,
    color10: colors.dark10,
    color11: colors.dark11,
    color12: colors.dark12,

    outline: colors.dark5,
    outlineVariant: colors.dark7,

    elevation: {
      level0: "transparent",
      level1: colors.light12,
      level2: colors.light11,
      level3: colors.light10,
      level4: colors.light10,
      level5: colors.light10,
    },

    red: colors.red,
    red1: colors.red1,
    red2: colors.red2,
    red3: colors.red3,
    red4: colors.red4,
    red5: colors.red5,
    red6: colors.red6,
    red7: colors.red7,
    red8: colors.red8,
    red9: colors.red9,
    red10: colors.red10,
    red11: colors.red11,
    red12: colors.red12,

    blue: colors.blue,
    blue1: colors.blue1,
    blue2: colors.blue2,
    blue3: colors.blue3,
    blue4: colors.blue4,
    blue5: colors.blue5,
    blue6: colors.blue6,
    blue7: colors.blue7,
    blue8: colors.blue8,
    blue9: colors.blue9,
    blue10: colors.blue10,
    blue11: colors.blue11,
    blue12: colors.blue12,

    purple: colors.purple,
    purple1: colors.purple1,
    purple2: colors.purple2,
    purple3: colors.purple3,
    purple4: colors.purple4,
    purple5: colors.purple5,
    purple6: colors.purple6,
    purple7: colors.purple7,
    purple8: colors.purple8,
    purple9: colors.purple9,
    purple10: colors.purple10,
    purple11: colors.purple11,
    purple12: colors.purple12,

    green: colors.green,
    green1: colors.green1,
    green2: colors.green2,
    green3: colors.green3,
    green4: colors.green4,
    green5: colors.green5,
    green6: colors.green6,
    green7: colors.green7,
    green8: colors.green8,
    green9: colors.green9,
    green10: colors.green10,
    green11: colors.green11,
    green12: colors.green12,

    yellow: colors.yellow,
    yellow1: colors.yellow1,
    yellow2: colors.yellow2,
    yellow3: colors.yellow3,
    yellow4: colors.yellow4,
    yellow5: colors.yellow5,
    yellow6: colors.yellow6,
    yellow7: colors.yellow7,
    yellow8: colors.yellow8,
    yellow9: colors.yellow9,
    yellow10: colors.yellow10,
    yellow11: colors.yellow11,
    yellow12: colors.yellow12,

    gray: colors.gray,
    gray1: colors.gray1,
    gray2: colors.gray2,
    gray3: colors.gray3,
    gray4: colors.gray4,
    gray5: colors.gray5,
    gray6: colors.gray6,
    gray7: colors.gray7,
    gray8: colors.gray8,
    gray9: colors.gray9,
    gray10: colors.gray10,
    gray11: colors.gray11,
    gray12: colors.gray12,

    pink: colors.pink,
    pink1: colors.pink1,
    pink2: colors.pink2,
    pink3: colors.pink3,
    pink4: colors.pink4,
    pink5: colors.pink5,
    pink6: colors.pink6,
    pink7: colors.pink7,
    pink8: colors.pink8,
    pink9: colors.pink9,
    pink10: colors.pink10,
    pink11: colors.pink11,
    pink12: colors.pink12,
  }
};
